name: Golee Gke Deploy Action Workflow
description: In order not to subscribe to the enterprise version of GitHub we publish our template actions here ;)
inputs:
  name:
    description: "App name"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
