name: Golee Gke Deploy Action Workflow
description: In order not to subscribe to the enterprise version of GitHub we publish our template actions here ;)
inputs:
  image_path:
    description: "Docker image"
    required: true
  platform:
    description: "Platform. Supported: gke, cloud-run"
    required: true
  repository:
    description: "Repository URL"
    required: true
  environment:
    description: "Environment name. Example: production, staging"
    required: true
  region:
    description: "Region. Example: europe-west8"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.image_path }}
    - ${{ inputs.platform }}
    - ${{ inputs.repository }}
    - ${{ inputs.environment }}
    - ${{ inputs.region }}
